### ISSUE TITLE
URL rewrite using dynamic data in JWT

### ISSUE THREAD

**Issue by platinummonkey** [platinummonkey/nginx-jwt#4]
clone from: https://github.com/auth0/nginx-jwt/issues/8

Leverage the URL rewrite capabilities of Nginx (ex: using the ngx_http_rewrite_module module) and perform a rewrite where the destination URL contains data from the JWT.

Example:
- The Nginx endpoint being called is /api/userinfo and the JWT passed by the client contains a field _user_id: sandrino123_
- The rewritten URL to the downstream endpoint becomes _https://server01/legacy/api/getuserinfofor/$user_id_ (where _$user_id_ is a value from the JWT in the Authorization header)

**Comment by hulu1522** [comment]
I just opened PR #7 as a solution to this issue.  It may not be what you are looking for but I thought I would give it a go.  I feel that any rewriting should be done by the client and that rewrites are out of the scope of this module.  The PR give users the ability to request the 'payload' table in order to perform any rewrites they need.
